apiVersion: v1
kind: ConfigMap
metadata:
  name: app-gateway-config
data:
  APP_NAME: gateway
  CLUSTER_NAME: hardhat
  ENV_NAME: local
  config.json: |
    {
      "SUPPORTED_NETWORKS": [
        {
          "name": "Local Hardhat",
          "type": "L1",
          "chainId": 31337,
          "endpoint": "http://localhost:9545",
          "oppositeChainId": null,
          "iconURL": "https://cryptologos.cc/logos/ethereum-eth-logo.png?v=010",
          "explorer": "http://localhost:8888/tx/"
        },
        {
          "name": "Local Tokamak",
          "type": "L2",
          "chainId": 2090,
          "endpoint": "http://localhost:8545",
          "oppositeChainId": 31337,
          "iconURL": "/logos/tokamak-symbol.svg",
          "explorer": "http://localhost:8080/tx/"
        }
      ],
      "SUPPORTED_TOKENS": [
        {
          "id": "ethereum",
          "chainId": 31337,
          "address": null,
          "name": "ETH",
          "symbol": "ETH",
          "decimals": 18,
          "iconURL": "https://cryptologos.cc/logos/ethereum-eth-logo.png?v=010",
          "extensions": {
            "optimismBridgeAddress": "0x610178dA211FEF7D417bC0e6FeD39F05609AD788"
          }
        },
        {
          "id": "ethereum",
          "chainId": 2090,
          "address": null,
          "name": "ETH",
          "symbol": "ETH",
          "decimals": 18,
          "iconURL": "https://cryptologos.cc/logos/ethereum-eth-logo.png?v=010",
          "extensions": {
            "optimismBridgeAddress": "0x4200000000000000000000000000000000000010"
          }
        }
      ],
      "SUPPORTED_CHAINID": [],
      "SUPPORTED_WALLETS": {
        "METAMASK": {
          "connector": "injected",
          "name": "MetaMask",
          "iconName": "metamask.svg",
          "description": "Easy-to-use browser extension.",
          "href": null,
          "color": "#E8831D",
          "type": "METAMASK"
        }
      }
    }
